DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product(
                                    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    title TEXT,
                                    description TEXT,
                                    price DOUBLE PRECISION
);