DROP TABLE IF EXISTS comment;

CREATE TABLE IF NOT EXISTS comment(
                                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      content TEXT,
                                      product_id int,
                                      FOREIGN KEY (product_id) REFERENCES product(id)
);