DROP TABLE IF EXISTS users;
DROP CAST IF EXISTS (VARCHAR AS role_enum);
DROP TYPE IF EXISTS role_enum;

CREATE TYPE role_enum AS ENUM ('USER','ADMIN');
CREATE CAST (VARCHAR AS role_enum) WITH INOUT AS IMPLICIT;

CREATE TABLE IF NOT EXISTS users(
                                    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    username VARCHAR,
                                    email VARCHAR,
                                    password VARCHAR,
                                    role role_enum,
                                    activation_code VARCHAR,
                                    is_activated BOOLEAN
);